const actionTypes = {
  GET_ALL_POSTS_REQUEST: "GET_ALL_POSTS_REQUEST",
  GET_ALL_POSTS_RECIVIED: "GET_ALL_POSTS_RECIVIED",

  GET_SINGLE_POST_REQUEST: "GET_SINGLE_POST_REQUEST",
  GET_SINGLE_POST_RECIVIED: "GET_SINGLE_POST_RECIVIED",

  GET_SINGLE_POST_COMMENTS_REQUEST: "GET_SINGLE_POST_COMMENTS_REQUEST",
  GET_SINGLE_POST_COMMENTS_RECIVIED: "GET_SINGLE_POST_COMMENTS_RECIVIED",
};

export default actionTypes;
